name: flutter_framework
description: A minimal Flutter framework scaffold created by assistant
publish_to: 'none'
version: 0.0.1
# environment should be flexible; user can adjust SDK version
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png
